weights: ./models/st_gcn.kinetics.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/val_data.npy
  label_path: ./data/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3 #3
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test
phase: test
device: 0
test_batch_size: 64
