work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# weights: ./models/st_gcn.kinetics.pt

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ./data/train_data.npy
  label_path: ./data/train_label.pkl
test_feeder_args:
  data_path: ./data/val_data.npy
  label_path: ./dataval_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 1 #3
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 256
test_batch_size: 256

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



